server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name admin.marqueeflow.com;

    root /var/www/marqueeflow/admin-panel/dist;
    index index.html;

    ssl_certificate /etc/letsencrypt/live/marqueeflow.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/marqueeflow.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80;
    listen [::]:80;
    server_name admin.marqueeflow.com;
    return 301 https://$host$request_uri;
}
