server {
    listen 80;
    listen [::]:80;
    server_name marqueeflow.com www.marqueeflow.com;

    root /var/www/marqueeflow/admin-panel/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
